/////////////////////////////////////////////////////////////////////////////
// Name:        src/gtk/menu.cpp
// Purpose:     implementation of wxMenuBar and wxMenu classes for wxGTK
// Author:      Robert Roebling
// Copyright:   (c) 1998 Robert Roebling
// Licence:     wxWindows licence
/////////////////////////////////////////////////////////////////////////////

// For compilers that support precompilation, includes "wx.h".
#include "wx/wxprec.h"

#if wxUSE_MENUS

#include "wx/menu.h"

#ifndef WX_PRECOMP
    #include "wx/intl.h"
    #include "wx/log.h"
    #include "wx/dialog.h"
    #include "wx/frame.h"
    #include "wx/bitmap.h"
    #include "wx/app.h"
#endif

#if wxUSE_ACCEL
    #include "wx/accel.h"

    #include <memory>
#endif // wxUSE_ACCEL

#include "wx/modalhook.h"
#include "wx/stockitem.h"

#include "wx/gtk/private.h"
#ifndef __WXGTK4__
    // wxGtkImage derives from GtkImage, which is an opaque type under GTK4;
    // it is only used for the bitmap of a GtkImageMenuItem here anyway, and
    // GTK4 menu item bitmaps are GIcons, see wxMenu::GTKRebuildModel().
    #include "wx/gtk/private/image.h"
#endif
#include "wx/gtk/private/mnemonics.h"

// we use normal item but with a special id for the menu title
static const int wxGTK_TITLE_ID = -3;

#if wxUSE_ACCEL
namespace
{

// Simple struct encapsulating a GTK accelerator with wrappers for just the
// operations that we need.
class GtkAccel
{
public:
    // Can be constructed from any menu item (must be valid, but doesn't have
    // to be an accelerator) or an already existing accelerator entry.
    explicit GtkAccel(const wxMenuItem* item);
    explicit GtkAccel(const wxAcceleratorEntry& entry) { Init(&entry); }

    // Default copy ctor, assignment operator and dtor are all OK.

    bool IsOk() const { return m_key != 0; }

#ifdef __WXGTK4__
    // GTK4 has no GtkAccelGroup: accelerators are GtkShortcuts built from the
    // key and modifiers, and displayed from the "accel" menu item attribute,
    // so the accelerator is used directly instead of being installed on a
    // widget.
    guint GetKey() const { return m_key; }
    GdkModifierType GetMods() const { return m_mods; }
#else
    void Add(GtkWidget* widget, GtkAccelGroup* accelGroup, GtkAccelFlags accelFlags);
    void Remove(GtkWidget* widget, GtkAccelGroup* accelGroup);
#endif // __WXGTK4__/!__WXGTK4__

private:
    static wxString GetGtkHotKey(const wxAcceleratorEntry*);

    void Init(const wxAcceleratorEntry* entry);

    guint m_key;
    GdkModifierType m_mods;
};

} // anonymous namespace

#endif // wxUSE_ACCEL

// Unity hack: under Ubuntu Unity the global menu bar is not affected by a
// modal dialog being shown, so the user can select a menu item before hiding
// the dialog and, in particular, a new instance of the same dialog can be
// shown again, breaking a lot of programs not expecting this.
//
// So explicitly ignore any menu events generated while any modal dialogs
// are opened except for the events generated by a context menu within the
// modal dialog itself that should have a dialog as their invoking window.
static bool IsMenuEventAllowed(wxMenu* menu)
{
    if ( wxModalDialogHook::GetOpenCount() )
    {
        wxWindow* tlw = wxGetTopLevelParent(menu->GetWindow());
        if ( !tlw || !wxDynamicCast(tlw, wxDialog) )
        {
            // This must be an event from a menu bar of one of the frames.
            return false;
        }
    }

    return true;
}

static void DoCommonMenuCallbackCode(wxMenu *menu, wxMenuEvent& event)
{
    if ( !IsMenuEventAllowed(menu) )
        return;

    wxMenu::ProcessMenuEvent(menu, event, menu->GetWindow());
}

// Return the top level menu containing this menu (possibly this menu itself).
static wxMenu* GetRootParentMenu(wxMenu* menu)
{
    while ( menu->GetParent() )
        menu = menu->GetParent();

    return menu;
}

#ifdef __WXGTK4__

// ============================================================================
// GTK4: GMenuModel + GAction
// ============================================================================
//
// GTK4 removed every menu widget class there was -- GtkMenu, GtkMenuBar,
// GtkMenuItem and all its subclasses, GtkAccelGroup and the gtk_menu_popup*()
// family -- and replaced them with something of a different shape: a
// GMenuModel describes the structure, GActions carry the behaviour and
// GtkPopoverMenu/GtkPopoverMenuBar are views rendering a model. There are no
// per-item widgets at all, so this is a rewrite of the backend rather than a
// translation of it. See docs/gtk/gtk4-phase-menu-design.md for the design and
// docs/gtk/probes/gtk4-menu-actions.c for the probe it is based on.

#include <string.h>

namespace
{

// Every menu gets a process-unique action group prefix and every item action a
// process-unique name: a menu may contain several items with the same wx ID
// and an item may be moved between menus, so wx IDs can't be used for this.
unsigned int gs_menuSerial = 0;
unsigned int gs_actionSerial = 0;

// Name of the never-enabled action used for the entries GTK4 can't disable by
// itself, see the design document.
const char* const wxGTK_DISABLED_ACTION = "disabled";

// Build a GIcon for a menu item bitmap. GMenuItem only accepts a GIcon, which
// looks at first like it rules out arbitrary bitmaps, but GdkTexture does
// implement GIcon, so it doesn't.
GIcon* MakeMenuIcon(const wxBitmapBundle& bundle, wxWindow* win)
{
    if ( !bundle.IsOk() )
        return nullptr;

    int scale = 1;
    if ( win )
    {
        const double factor = win->GetContentScaleFactor();
        if ( factor > 1 )
            scale = int(factor + 0.5);
    }

    const wxBitmap bmp = bundle.GetBitmap(bundle.GetDefaultSize() * scale);
    if ( !bmp.IsOk() )
        return nullptr;

    GdkPixbuf* const pixbuf = bmp.GetPixbuf();
    if ( !pixbuf )
        return nullptr;

    // gdk_texture_new_for_pixbuf() takes its own reference to the pixels, so
    // the pixbuf owned by the bitmap doesn't need to be kept alive here.
    return G_ICON(gdk_texture_new_for_pixbuf(pixbuf));
}

// Return the GSimpleAction backing this item, if it has one: separators and
// sub menu items don't, and neither does an item not added to a menu yet.
GSimpleAction* FindItemAction(const wxMenuItem* item)
{
    wxMenu* const menu = item->GetMenu();
    if ( !menu || item->GTKGetActionName().empty() )
        return nullptr;

    GAction* const action =
        g_action_map_lookup_action(G_ACTION_MAP(menu->GTKGetActionGroup()),
                                   item->GTKGetActionName().utf8_str());

    return action ? G_SIMPLE_ACTION(action) : nullptr;
}

// Common part of the action callbacks below: send the wx event for this item.
void ActivateMenuItem(wxMenuItem* item, int checked)
{
    if ( !item->IsEnabled() )
        return;

    if ( !IsMenuEventAllowed(item->GetMenu()) )
        return;

    const int id = item->GetId();
    if ( id == wxGTK_TITLE_ID )
    {
        // ignore events from the menu title
        return;
    }

    item->GetMenu()->SendEvent(id, checked);

    // A lot of existing code, including any program that closes its main
    // window from a menu handler and expects the program to exit -- as our own
    // minimal sample -- relies on getting an idle event after a menu event.
    wxWakeUpIdle();
}

// Data shared with the popover callbacks for the duration of a popup menu.
struct PopupData
{
    wxMenu* menu;
    GMainLoop* loop;
};

} // anonymous namespace

extern "C" {

// "activate" of the action of a normal menu item
static void wx_menu_item_activate(GSimpleAction*, GVariant*, gpointer user_data)
{
    ActivateMenuItem(static_cast<wxMenuItem*>(user_data), -1);
}

// "change-state" of the action of a check menu item: connecting to this rather
// than to "activate" means that wxMenuItem::Check() can update the state with
// g_simple_action_set_state(), which doesn't emit it, without sending an event
static void wx_menu_check_state(GSimpleAction* action,
                                GVariant* value,
                                gpointer user_data)
{
    wxMenuItem* const item = static_cast<wxMenuItem*>(user_data);

    g_simple_action_set_state(action, value);

    const bool checked = g_variant_get_boolean(value) != 0;

    // Ensure that the internal state is always consistent with what is shown.
    item->wxMenuItemBase::Check(checked);

    ActivateMenuItem(item, checked);
}

// "change-state" of the action shared by a whole radio group
static void wx_menu_radio_state(GSimpleAction* action,
                                GVariant* value,
                                gpointer user_data)
{
    wxMenu* const menu = static_cast<wxMenu*>(user_data);

    g_simple_action_set_state(action, value);

    menu->GTKOnRadioSelected(g_action_get_name(G_ACTION(action)),
                             wxString::FromUTF8(g_variant_get_string(value,
                                                                     nullptr)));
}

// "show" of the popover used for a popup menu
static void wx_menu_popover_show(GtkWidget*, gpointer user_data)
{
    PopupData* const data = static_cast<PopupData*>(user_data);

    data->menu->UpdateUI();

    wxMenuEvent event(wxEVT_MENU_OPEN, -1, data->menu);
    DoCommonMenuCallbackCode(data->menu, event);
}

// "closed" of the popover used for a popup menu
static void wx_menu_popover_closed(GtkPopover*, gpointer user_data)
{
    PopupData* const data = static_cast<PopupData*>(user_data);

    if ( g_main_loop_is_running(data->loop) )
        g_main_loop_quit(data->loop);
}

} // extern "C"

//-----------------------------------------------------------------------------
// wxMenuBar
//-----------------------------------------------------------------------------

wxMenuBar::~wxMenuBar()
{
    g_object_unref(m_barModel);
}

void wxMenuBar::Init(size_t n, wxMenu *menus[], const wxString titles[], long style)
{
    // Do this before the check below: the dtor unrefs the model unconditionally
    // and creation can fail.
    m_barModel = g_menu_new();
    m_shortcuts = nullptr;

    if (!PreCreation( nullptr, wxDefaultPosition, wxDefaultSize ) ||
        !CreateBase( nullptr, -1, wxDefaultPosition, wxDefaultSize, style, wxDefaultValidator, wxT("menubar") ))
    {
        wxFAIL_MSG( wxT("wxMenuBar creation failed") );
        return;
    }

    // Note that wxMB_DOCKABLE is silently ignored: it was implemented using
    // GtkHandleBox, which is gone, and it was already ignored with
    // GTK+ >= 3.19.7 because using it prevented the menu bar from drawing.
    m_menubar = gtk_popover_menu_bar_new_from_model(G_MENU_MODEL(m_barModel));
    m_widget = m_menubar;

    PostCreation();

    g_object_ref_sink(m_widget);

    for (size_t i = 0; i < n; ++i )
        Append(menus[i], titles[i]);
}

wxMenuBar::wxMenuBar(size_t n, wxMenu *menus[], const wxString titles[], long style)
{
    Init(n, menus, titles, style);
}

wxMenuBar::wxMenuBar(long style)
{
    Init(0, nullptr, nullptr, style);
}

wxMenuBar::wxMenuBar()
{
    Init(0, nullptr, nullptr, 0);
}

namespace
{

// Return the widget the menu actions must be installed on. Named actions are
// resolved by walking up the widget hierarchy from the widget using them, so
// this has to be an ancestor of both the menu bar and the shortcut controller,
// i.e. the TLW: note that the frame may be an MDI child frame, which is a fake
// frame and not a TLW at all, hence wxGetTopLevelParent().
GtkWidget* GetActionTarget(wxWindow* frame)
{
    wxWindow* const tlw = frame ? wxGetTopLevelParent(frame) : nullptr;

    return tlw ? tlw->m_widget : nullptr;
}

} // anonymous namespace

void wxMenuBar::GTKRebuildModel()
{
    // The model is regenerated from scratch rather than patched, see the
    // design document: GMenu copies item attributes when the item is inserted,
    // so there is nothing to update in place.
    g_menu_remove_all(m_barModel);

    for ( wxMenuList::compatibility_iterator node = m_menus.GetFirst();
          node;
          node = node->GetNext() )
    {
        wxMenu* const menu = node->GetData();
        const wxString title(wxConvertMnemonicsToGTK(menu->GetTitle()));

        if ( menu->GTKIsEnabledTop() )
        {
            g_menu_append_submenu(m_barModel, title.utf8_str(),
                                  G_MENU_MODEL(menu->GTKGetMenuModel()));
        }
        else
        {
            // The label stays a submenu, with nothing in it.
            //
            // A GtkPopoverMenuBar renders only submenus at the top level. An
            // item bound to a never-enabled action, which is the obvious way
            // to show a disabled title, is refused with "Don't know how to
            // handle this item" -- and refusing it costs more than the grey:
            // the label is dropped from the bar altogether, and the menus
            // after it come out in the wrong order, because the tracker's
            // bookkeeping does not survive an item it would not take. See
            // #253.
            //
            // So this is a trade rather than a fix for everything: the title
            // is in its place and opens on to nothing, where GTK+ 3 greys it
            // out and does not open. A submenu item has no action and no
            // disabled state under GTK4, so looking disabled is not something
            // the menu bar can be asked for.
            GMenu* const empty = g_menu_new();
            g_menu_append_submenu(m_barModel, title.utf8_str(),
                                  G_MENU_MODEL(empty));
            g_object_unref(empty);
        }
    }

    // The items, and hence their accelerators, may have changed together with
    // the model, so the shortcuts have to be regenerated as well.
    GtkWidget* const target = GetActionTarget(m_menuBarFrame);
    if ( !target )
        return;

    GTKRemoveShortcuts(target);

#if wxUSE_ACCEL
    m_shortcuts = gtk_shortcut_controller_new();
    gtk_shortcut_controller_set_scope(GTK_SHORTCUT_CONTROLLER(m_shortcuts),
                                      GTK_SHORTCUT_SCOPE_GLOBAL);
    gtk_widget_add_controller(target, m_shortcuts);

    // The widget owns the controller now, so this pointer has to stop
    // pointing at it if the widget takes it down first: removing a
    // controller that has already been destroyed is what GTK reports as
    // "assertion 'GTK_IS_EVENT_CONTROLLER (controller)' failed".
    g_object_add_weak_pointer(G_OBJECT(m_shortcuts),
                              reinterpret_cast<gpointer*>(&m_shortcuts));

    for ( wxMenuList::compatibility_iterator node = m_menus.GetFirst();
          node;
          node = node->GetNext() )
    {
        node->GetData()->
            GTKAddShortcuts(GTK_SHORTCUT_CONTROLLER(m_shortcuts));
    }
#endif // wxUSE_ACCEL
}

#else // !__WXGTK4__

// Call SetGtkLabel() to update the labels of all the items in this items sub
// menu, recursively.
static void UpdateSubMenuItemLabels(wxMenuItem* itemMenu)
{
    wxMenu* const menu = itemMenu->GetSubMenu();
    wxCHECK_RET( menu, "should only be called for sub menus" );

    const wxMenuItemList& items = menu->GetMenuItems();
    for ( auto* item : items )
    {
        if ( !item->IsSeparator() )
        {
            item->SetGtkLabel();
            if ( item->IsSubMenu() )
                UpdateSubMenuItemLabels(item);
        }
    }
}

//-----------------------------------------------------------------------------
// wxMenuBar
//-----------------------------------------------------------------------------

wxMenuBar::~wxMenuBar()
{
}

void wxMenuBar::Init(size_t n, wxMenu *menus[], const wxString titles[], long style)
{
    if (!PreCreation( nullptr, wxDefaultPosition, wxDefaultSize ) ||
        !CreateBase( nullptr, -1, wxDefaultPosition, wxDefaultSize, style, wxDefaultValidator, wxT("menubar") ))
    {
        wxFAIL_MSG( wxT("wxMenuBar creation failed") );
        return;
    }

    m_menubar = gtk_menu_bar_new();

#ifndef __WXGTK4__
    if ((style & wxMB_DOCKABLE)
#ifdef __WXGTK3__
        // using GtkHandleBox prevents menubar from drawing with GTK+ >= 3.19.7
        && gtk_check_version(3,19,7)
#endif
        )
    {
        wxGCC_WARNING_SUPPRESS(deprecated-declarations)
        m_widget = gtk_handle_box_new();
        wxGCC_WARNING_RESTORE()
        gtk_container_add(GTK_CONTAINER(m_widget), m_menubar);
        gtk_widget_set_visible(m_menubar, TRUE);
    }
    else
#endif
    {
        m_widget = m_menubar;
    }

    PostCreation();

    g_object_ref_sink(m_widget);

    for (size_t i = 0; i < n; ++i )
        Append(menus[i], titles[i]);
}

wxMenuBar::wxMenuBar(size_t n, wxMenu *menus[], const wxString titles[], long style)
{
    Init(n, menus, titles, style);
}

wxMenuBar::wxMenuBar(long style)
{
    Init(0, nullptr, nullptr, style);
}

wxMenuBar::wxMenuBar()
{
    Init(0, nullptr, nullptr, 0);
}

// recursive helpers for wxMenuBar::Attach() and Detach(): they are called to
// associate the menus with the frame they belong to or dissociate them from it
namespace
{

// This should be called when detaching menus to ensure that they don't keep
// focus grab, because if they do, they continue getting all GTK+ messages
// which they can't process any more in their (soon to be) unrealized state.
void
EnsureNoGrab(GtkWidget* widget)
{
    gtk_widget_set_visible(widget, FALSE);
    gtk_grab_remove(widget);
}

void
DetachFromFrame(wxMenu* menu, wxFrame* frame)
{
    // support for native hot keys
    if (menu->m_accel)
    {
        // Note that wxGetTopLevelParent() is really needed because this frame
        // can be an MDI child frame which is a fake frame and not a TLW at all
        GtkWindow * const tlw = GTK_WINDOW(wxGetTopLevelParent(frame)->m_widget);
        if (g_slist_find(gtk_accel_groups_from_object(G_OBJECT(tlw)), menu->m_accel))
            gtk_window_remove_accel_group(tlw, menu->m_accel);
    }

    wxMenuItemList::compatibility_iterator node = menu->GetMenuItems().GetFirst();
    while (node)
    {
        wxMenuItem *menuitem = node->GetData();
        if (menuitem->IsSubMenu())
            DetachFromFrame(menuitem->GetSubMenu(), frame);
        node = node->GetNext();
    }

    EnsureNoGrab(menu->m_menu);
}

void
AttachToFrame(wxMenu* menu, wxFrame* frame)
{
    // support for native hot keys
    if (menu->m_accel)
    {
        GtkWindow * const tlw = GTK_WINDOW(wxGetTopLevelParent(frame)->m_widget);
        if (!g_slist_find(gtk_accel_groups_from_object(G_OBJECT(tlw)), menu->m_accel))
            gtk_window_add_accel_group(tlw, menu->m_accel);
    }

    wxMenuItemList::compatibility_iterator node = menu->GetMenuItems().GetFirst();
    while (node)
    {
        wxMenuItem *menuitem = node->GetData();
        if (menuitem->IsSubMenu())
            AttachToFrame(menuitem->GetSubMenu(), frame);
        node = node->GetNext();
    }

    menu->SetupBitmaps(frame);
}

} // anonymous namespace

#endif // __WXGTK4__/!__WXGTK4__

void wxMenuBar::SetLayoutDirection(wxLayoutDirection dir)
{
    if ( dir == wxLayout_Default )
    {
        const wxWindow *const frame = GetFrame();
        if ( frame )
        {
            // inherit layout from frame.
            dir = frame->GetLayoutDirection();
        }
        else // use global layout
        {
            dir = wxTheApp->GetLayoutDirection();
        }
    }

    if ( dir == wxLayout_Default )
        return;

    GTKSetLayout(m_menubar, dir);

    // also set the layout of all menus we already have (new ones will inherit
    // the current layout)
    for ( wxMenuList::compatibility_iterator node = m_menus.GetFirst();
          node;
          node = node->GetNext() )
    {
        wxMenu *const menu = node->GetData();
        menu->SetLayoutDirection(dir);
    }
}

wxLayoutDirection wxMenuBar::GetLayoutDirection() const
{
    return GTKGetLayout(m_menubar);
}

#ifdef __WXGTK4__

void wxMenuBar::Attach(wxFrame *frame)
{
    wxMenuBarBase::Attach(frame);

    if ( GtkWidget* const target = GetActionTarget(frame) )
    {
        for ( wxMenuList::compatibility_iterator node = m_menus.GetFirst();
              node;
              node = node->GetNext() )
        {
            wxMenu* const menu = node->GetData();
            menu->GTKInstallActions(target);
            menu->SetupBitmaps(frame);
        }
    }

    // This also registers the shortcuts for our accelerators, which could only
    // be done once we knew which widget to install them on.
    GTKRebuildModel();

    SetLayoutDirection(wxLayout_Default);
}

// Take the shortcut controller off the widget that has it, if any. Does
// nothing once the widget has been destroyed, as it took the controller with
// it and m_shortcuts is null again by then.
void wxMenuBar::GTKRemoveShortcuts(GtkWidget* target)
{
    if ( !m_shortcuts )
        return;

    GtkEventController* const shortcuts = m_shortcuts;

    // Stop watching before removing: removing is what destroys it.
    g_object_remove_weak_pointer(G_OBJECT(shortcuts),
                                 reinterpret_cast<gpointer*>(&m_shortcuts));
    m_shortcuts = nullptr;

    gtk_widget_remove_controller(target, shortcuts);
}

void wxMenuBar::Detach()
{
    if ( GtkWidget* const target = GetActionTarget(m_menuBarFrame) )
    {
        GTKRemoveShortcuts(target);

        for ( wxMenuList::compatibility_iterator node = m_menus.GetFirst();
              node;
              node = node->GetNext() )
        {
            node->GetData()->GTKUninstallActions(target);
        }
    }

    wxMenuBarBase::Detach();
}

void wxMenuBar::GtkAppend(wxMenu* menu, const wxString& title, int pos)
{
    // The position is not used: the model is regenerated from the menu list,
    // which the base class has already updated.
    wxUnusedVar(pos);

    menu->SetTitle( title );

    if ( GtkWidget* const target = GetActionTarget(m_menuBarFrame) )
    {
        menu->GTKInstallActions(target);
        menu->SetupBitmaps(m_menuBarFrame);
    }

    GTKRebuildModel();
}

wxMenu *wxMenuBar::Remove(size_t pos)
{
    wxMenu *menu = wxMenuBarBase::Remove(pos);
    if ( !menu )
        return nullptr;

    if ( GtkWidget* const target = GetActionTarget(m_menuBarFrame) )
        menu->GTKUninstallActions(target);

    GTKRebuildModel();

    return menu;
}

#else // !__WXGTK4__

void wxMenuBar::Attach(wxFrame *frame)
{
    wxMenuBarBase::Attach(frame);

    wxMenuList::compatibility_iterator node = m_menus.GetFirst();
    while (node)
    {
        wxMenu *menu = node->GetData();
        AttachToFrame( menu, frame );
        node = node->GetNext();
    }

    SetLayoutDirection(wxLayout_Default);
}

void wxMenuBar::Detach()
{
    wxMenuList::compatibility_iterator node = m_menus.GetFirst();
    while (node)
    {
        wxMenu *menu = node->GetData();
        DetachFromFrame( menu, m_menuBarFrame );
        node = node->GetNext();
    }

    EnsureNoGrab(m_widget);

    wxMenuBarBase::Detach();
}

#endif // __WXGTK4__/!__WXGTK4__

bool wxMenuBar::Append( wxMenu *menu, const wxString &title )
{
    if (wxMenuBarBase::Append(menu, title))
    {
        GtkAppend(menu, title);
        return true;
    }
    return false;
}

#ifndef __WXGTK4__

void wxMenuBar::GtkAppend(wxMenu* menu, const wxString& title, int pos)
{
    menu->SetLayoutDirection(GetLayoutDirection());

    {
        // This doesn't have much effect right now.
        menu->SetTitle( title );

        const wxString str(wxConvertMnemonicsToGTK(title));
        // The "m_owner" is the "menu item"
        menu->m_owner = gtk_menu_item_new_with_mnemonic( str.utf8_str() );

        gtk_menu_item_set_submenu( GTK_MENU_ITEM(menu->m_owner), menu->m_menu );
    }
    g_object_ref(menu->m_owner);

    gtk_widget_set_visible(menu->m_owner, TRUE);

    if (pos == -1)
        gtk_menu_shell_append( GTK_MENU_SHELL(m_menubar), menu->m_owner );
    else
        gtk_menu_shell_insert( GTK_MENU_SHELL(m_menubar), menu->m_owner, pos );

    if ( m_menuBarFrame )
        AttachToFrame( menu, m_menuBarFrame );
}

#endif // !__WXGTK4__

bool wxMenuBar::Insert(size_t pos, wxMenu *menu, const wxString& title)
{
    if (wxMenuBarBase::Insert(pos, menu, title))
    {
        GtkAppend(menu, title, int(pos));
        return true;
    }
    return false;
}

wxMenu *wxMenuBar::Replace(size_t pos, wxMenu *menu, const wxString& title)
{
    // remove the old item and insert a new one
    wxMenu *menuOld = Remove(pos);
    if ( menuOld && !Insert(pos, menu, title) )
    {
        return nullptr;
    }

    // either Insert() succeeded or Remove() failed and menuOld is null
    return menuOld;
}

#ifndef __WXGTK4__

wxMenu *wxMenuBar::Remove(size_t pos)
{
    wxMenu *menu = wxMenuBarBase::Remove(pos);
    if ( !menu )
        return nullptr;

    // remove item from menubar before destroying item to avoid spurious
    // warnings from Ubuntu libdbusmenu
    gtk_container_remove(GTK_CONTAINER(m_menubar), menu->m_owner);
    // remove submenu to avoid destroying it when item is destroyed
#ifdef __WXGTK3__
    gtk_menu_item_set_submenu(GTK_MENU_ITEM(menu->m_owner), nullptr);
#else
    gtk_menu_item_remove_submenu(GTK_MENU_ITEM(menu->m_owner));
#endif

    gtk_widget_destroy( menu->m_owner );
    g_object_unref(menu->m_owner);
    menu->m_owner = nullptr;

    if ( m_menuBarFrame )
        DetachFromFrame( menu, m_menuBarFrame );

    return menu;
}

#endif // !__WXGTK4__

static int FindMenuItemRecursive( const wxMenu *menu, const wxString &menuString, const wxString &itemString )
{
    if (wxMenuItem::GetLabelText(menu->GetTitle()) == wxMenuItem::GetLabelText(menuString))
    {
        int res = menu->FindItem( itemString );
        if (res != wxNOT_FOUND)
            return res;
    }

    wxMenuItemList::compatibility_iterator node = menu->GetMenuItems().GetFirst();
    while (node)
    {
        wxMenuItem *item = node->GetData();
        if (item->IsSubMenu())
            return FindMenuItemRecursive(item->GetSubMenu(), menuString, itemString);

        node = node->GetNext();
    }

    return wxNOT_FOUND;
}

int wxMenuBar::FindMenuItem( const wxString &menuString, const wxString &itemString ) const
{
    wxMenuList::compatibility_iterator node = m_menus.GetFirst();
    while (node)
    {
        wxMenu *menu = node->GetData();
        int res = FindMenuItemRecursive( menu, menuString, itemString);
        if (res != -1)
            return res;
        node = node->GetNext();
    }

    return wxNOT_FOUND;
}

// Find a wxMenuItem using its id. Recurses down into sub-menus
static wxMenuItem* FindMenuItemByIdRecursive(const wxMenu* menu, int id)
{
    wxMenuItem* result = menu->FindChildItem(id);

    wxMenuItemList::compatibility_iterator node = menu->GetMenuItems().GetFirst();
    while ( node && result == nullptr )
    {
        wxMenuItem *item = node->GetData();
        if (item->IsSubMenu())
        {
            result = FindMenuItemByIdRecursive( item->GetSubMenu(), id );
        }
        node = node->GetNext();
    }

    return result;
}

wxMenuItem* wxMenuBar::FindItem( int id, wxMenu **menuForItem ) const
{
    wxMenuItem* result = nullptr;
    wxMenuList::compatibility_iterator node = m_menus.GetFirst();
    while (node && result == nullptr)
    {
        wxMenu *menu = node->GetData();
        result = FindMenuItemByIdRecursive( menu, id );
        node = node->GetNext();
    }

    if ( menuForItem )
    {
        *menuForItem = result ? result->GetMenu() : nullptr;
    }

    return result;
}

#ifdef __WXGTK4__

void wxMenuBar::EnableTop( size_t pos, bool flag )
{
    wxMenuList::compatibility_iterator node = m_menus.Item( pos );

    wxCHECK_RET( node, wxT("menu not found") );

    wxMenu* const menu = node->GetData();
    if ( menu->GTKIsEnabledTop() == flag )
        return;

    // There is no GTK state to set here: a GMenuModel sub menu item has no
    // action, so the model itself has to change, see GTKRebuildModel().
    menu->GTKSetEnabledTop(flag);

    GTKRebuildModel();
}

bool wxMenuBar::IsEnabledTop(size_t pos) const
{
    wxMenuList::compatibility_iterator node = m_menus.Item( pos );
    wxCHECK_MSG( node, false, wxS("invalid index in IsEnabledTop") );

    // Unlike with GTK3, this can't be read back from GTK, see above.
    return node->GetData()->GTKIsEnabledTop();
}

#else // !__WXGTK4__

void wxMenuBar::EnableTop( size_t pos, bool flag )
{
    wxMenuList::compatibility_iterator node = m_menus.Item( pos );

    wxCHECK_RET( node, wxT("menu not found") );

    wxMenu* menu = node->GetData();

    if (menu->m_owner)
        gtk_widget_set_sensitive( menu->m_owner, flag );
}

bool wxMenuBar::IsEnabledTop(size_t pos) const
{
    wxMenuList::compatibility_iterator node = m_menus.Item( pos );
    wxCHECK_MSG( node, false, wxS("invalid index in IsEnabledTop") );
    wxMenu* const menu = node->GetData();
    wxCHECK_MSG( menu->m_owner, true, wxS("no menu owner?") );
    return gtk_widget_get_sensitive( menu->m_owner ) != 0;
}

#endif // __WXGTK4__/!__WXGTK4__

wxString wxMenuBar::GetMenuLabel( size_t pos ) const
{
    wxMenuList::compatibility_iterator node = m_menus.Item( pos );

    wxCHECK_MSG( node, wxT("invalid"), wxT("menu not found") );

    wxMenu* menu = node->GetData();

    return menu->GetTitle();
}

void wxMenuBar::SetMenuLabel( size_t pos, const wxString& label )
{
    wxMenuList::compatibility_iterator node = m_menus.Item( pos );

    wxCHECK_RET( node, wxT("menu not found") );

    wxMenu* menu = node->GetData();

    menu->SetTitle( label );

#ifdef __WXGTK4__
    // The label is an attribute of the model item, which GMenu copied when it
    // was inserted, so it can only be changed by regenerating the model.
    GTKRebuildModel();
#else
    const wxString str(wxConvertMnemonicsToGTK(label));
    if (menu->m_owner)
        gtk_label_set_text_with_mnemonic(GTK_LABEL(gtk_bin_get_child(GTK_BIN(menu->m_owner))), str.utf8_str());
#endif
}

#ifndef __WXGTK4__

//-----------------------------------------------------------------------------
// "activate"
//-----------------------------------------------------------------------------

extern "C" {
static void menuitem_activate(GtkWidget*, wxMenuItem* item)
{
    if (!item->IsEnabled())
        return;

    if ( !IsMenuEventAllowed(item->GetMenu()) )
        return;

    int id = item->GetId();
    if (id == wxGTK_TITLE_ID)
    {
        // ignore events from the menu title
        return;
    }

    if (item->IsCheckable())
    {
        bool isReallyChecked = item->IsChecked(),
            isInternallyChecked = item->wxMenuItemBase::IsChecked();

        // ensure that the internal state is always consistent with what is
        // shown on the screen
        item->wxMenuItemBase::Check(isReallyChecked);

        // we must not report the events for the radio button going up nor the
        // events resulting from the calls to wxMenuItem::Check()
        if ( (item->GetKind() == wxITEM_RADIO && !isReallyChecked) ||
             (isInternallyChecked == isReallyChecked) )
        {
            return;
        }
    }

    wxMenu* menu = item->GetMenu();
    menu->SendEvent(id, item->IsCheckable() ? item->IsChecked() : -1);

    // A lot of existing code, including any program that closes its main
    // window from a menu handler and expects the program to exit -- as our own
    // minimal sample -- relies on getting an idle event after a menu event.
    // But when using Ubuntu Unity detached menus, we get called from a DBUS
    // handler called from g_timeout_dispatch() and Glib doesn't send us any
    // idle events after it. So ask explicitly for an idle event to get one.
    wxWakeUpIdle();
}
}

//-----------------------------------------------------------------------------
// "select"
//-----------------------------------------------------------------------------

extern "C" {
static void menuitem_select(GtkWidget*, wxMenuItem* item)
{
    if (!item->IsEnabled())
        return;

    wxMenuEvent event(wxEVT_MENU_HIGHLIGHT, item->GetId(), item->GetMenu());
    DoCommonMenuCallbackCode(item->GetMenu(), event);
}
}

//-----------------------------------------------------------------------------
// "deselect"
//-----------------------------------------------------------------------------

extern "C" {
static void menuitem_deselect(GtkWidget*, wxMenuItem* item)
{
    if (!item->IsEnabled())
        return;

    wxMenuEvent event(wxEVT_MENU_HIGHLIGHT, wxID_NONE, item->GetMenu());
    DoCommonMenuCallbackCode(item->GetMenu(), event);
}
}

#endif // !__WXGTK4__

//-----------------------------------------------------------------------------
// wxMenuItem
//-----------------------------------------------------------------------------

wxMenuItem *wxMenuItemBase::New(wxMenu *parentMenu,
                                int id,
                                const wxString& name,
                                const wxString& help,
                                wxItemKind kind,
                                wxMenu *subMenu)
{
    return new wxMenuItem(parentMenu, id, name, help, kind, subMenu);
}

#ifdef __WXGTK4__

wxMenuItem::wxMenuItem(wxMenu *parentMenu,
                       int id,
                       const wxString& text,
                       const wxString& help,
                       wxItemKind kind,
                       wxMenu *subMenu)
          : wxMenuItemBase(parentMenu, id, text, help, kind, subMenu)
{
    m_bitmapWin = nullptr;
}

wxMenuItem::~wxMenuItem()
{
    // Nothing to do: our action belongs to the action group of our menu and is
    // dropped when the menu regenerates its model without us in it.
}

void wxMenuItem::SetItemLabel( const wxString& str )
{
    wxMenuItemBase::SetItemLabel(str);

    SetGtkLabel();
}

void wxMenuItem::SetGtkLabel()
{
    // Both the label and the accelerator shown next to it are attributes of
    // the menu model item, which GMenu copied when the item was inserted, so
    // the model has to be regenerated for the change to be visible.
    if ( m_parentMenu )
        m_parentMenu->GTKRebuildModel();
}

#if wxUSE_ACCEL

void wxMenuItem::GTKSetExtraAccels()
{
    // Nothing to do here: unlike GTK3, which needed each accelerator to be
    // added to the item widget, GTK4 shortcuts are all (re)created together by
    // wxMenuBar::GTKRebuildModel() from wxMenuItem::GetExtraAccels().
}

void wxMenuItem::AddExtraAccel(const wxAcceleratorEntry& accel)
{
    wxMenuItemBase::AddExtraAccel(accel);

    if ( m_parentMenu )
        m_parentMenu->GTKRebuildModel();
}

void wxMenuItem::ClearExtraAccels()
{
    wxMenuItemBase::ClearExtraAccels();

    if ( m_parentMenu )
        m_parentMenu->GTKRebuildModel();
}

#endif // wxUSE_ACCEL

void wxMenuItem::SetupBitmaps(wxWindow *win)
{
    // Just remember the window: the icon is only put into the model when it is
    // (re)built, as GMenuItem attributes can't be changed after insertion.
    // wxMenu::SetupBitmaps() triggers that rebuild once for the whole menu.
    m_bitmapWin = win;
}

void wxMenuItem::Check( bool check )
{
    if (check == m_isChecked)
        return;

    switch ( GetKind() )
    {
        case wxITEM_RADIO:
            // It doesn't make sense to uncheck a radio item.
            if ( !check )
                return;

            wxFALLTHROUGH;
        case wxITEM_CHECK:
            wxMenuItemBase::Check( check );

            if ( GSimpleAction* const action = FindItemAction(this) )
            {
                // Set the state directly instead of going through the action
                // group: this must not emit "change-state" and so must not
                // result in a wx event being sent from here.
                if ( GetKind() == wxITEM_RADIO )
                {
                    g_simple_action_set_state(
                        action, g_variant_new_string(m_radioTarget.utf8_str()));

                    // The rest of the group is implicitly unchecked now as far
                    // as GTK is concerned, so keep our own flags in sync.
                    if ( m_parentMenu )
                    {
                        for ( auto* sibling : m_parentMenu->GetMenuItems() )
                        {
                            if ( sibling != this &&
                                 sibling->GetKind() == wxITEM_RADIO &&
                                 sibling->m_actionName == m_actionName )
                            {
                                sibling->wxMenuItemBase::Check(false);
                            }
                        }
                    }
                }
                else
                {
                    g_simple_action_set_state(action,
                                              g_variant_new_boolean(check));
                }
            }
            break;

        default:
            wxFAIL_MSG( wxT("can't check this item") );
    }
}

void wxMenuItem::Enable( bool enable )
{
    wxMenuItemBase::Enable( enable );

    if ( GSimpleAction* const action = FindItemAction(this) )
    {
        // Note that disabling a radio item disables its whole group: GTK4
        // radio items in a group share a single action and it is the action
        // which carries the enabled state.
        g_simple_action_set_enabled(action, enable);
    }
    else if ( m_parentMenu && IsSubMenu() )
    {
        // A sub menu item has no action to disable, so the model itself has to
        // change: wxMenu::GTKRebuildModel() emits a disabled sub menu as a
        // plain item bound to the menu's never-enabled action.
        m_parentMenu->GTKRebuildModel();
    }
}

bool wxMenuItem::IsChecked() const
{
    wxCHECK_MSG( IsCheckable(), false,
                 wxT("can't get state of uncheckable item!") );

    GSimpleAction* const action = FindItemAction(this);
    if ( !action )
    {
        // Not added to a menu yet, so all we have is our own flag.
        return wxMenuItemBase::IsChecked();
    }

    GVariant* const state = g_action_get_state(G_ACTION(action));
    if ( !state )
        return wxMenuItemBase::IsChecked();

    bool checked;
    if ( GetKind() == wxITEM_RADIO )
    {
        checked = m_radioTarget ==
                    wxString::FromUTF8(g_variant_get_string(state, nullptr));
    }
    else
    {
        checked = g_variant_get_boolean(state) != 0;
    }

    g_variant_unref(state);

    return checked;
}

#else // !__WXGTK4__

wxMenuItem::wxMenuItem(wxMenu *parentMenu,
                       int id,
                       const wxString& text,
                       const wxString& help,
                       wxItemKind kind,
                       wxMenu *subMenu)
          : wxMenuItemBase(parentMenu, id, text, help, kind, subMenu)
{
    m_menuItem = nullptr;
}

wxMenuItem::~wxMenuItem()
{
    if (m_menuItem)
        g_object_unref(m_menuItem);
   // don't delete menu items, the menus take care of that
}

void wxMenuItem::SetMenuItem(GtkWidget* menuItem)
{
    if (m_menuItem)
        g_object_unref(m_menuItem);
    m_menuItem = menuItem;
    if (menuItem)
        g_object_ref(menuItem);
    if (m_menuItem && m_parentMenu && m_parentMenu->GetWindow())
        SetupBitmaps(m_parentMenu->GetWindow());
}

void wxMenuItem::SetItemLabel( const wxString& str )
{
#if wxUSE_ACCEL
    if (m_menuItem)
    {
        // remove old accelerator
        GtkAccel gtkAccel(this);
        if ( gtkAccel.IsOk() )
        {
            gtkAccel.Remove(m_menuItem, GetRootParentMenu(m_parentMenu)->m_accel);
        }
    }
#endif // wxUSE_ACCEL
    wxMenuItemBase::SetItemLabel(str);
    if (m_menuItem)
        SetGtkLabel();
}

void wxMenuItem::SetGtkLabel()
{
    const wxString text = wxConvertMnemonicsToGTK(m_text.BeforeFirst('\t'));
    GtkLabel* label = GTK_LABEL(gtk_bin_get_child(GTK_BIN(m_menuItem)));
    gtk_label_set_text_with_mnemonic(label, text.utf8_str());
#if wxUSE_ACCEL
    GtkAccel gtkAccel(this);
    if ( gtkAccel.IsOk() )
    {
        gtkAccel.Add(m_menuItem, GetRootParentMenu(m_parentMenu)->m_accel,
                     GTK_ACCEL_VISIBLE);
    }
    else
    {
        // Remove the accelerator since it couldn't be made or is invalid
        m_text = m_text.BeforeFirst( wxS( '\t' ) );
    }
#endif // wxUSE_ACCEL
}

#if wxUSE_ACCEL
void wxMenuItem::GTKSetExtraAccels()
{
    GtkAccelGroup* const accelGroup = GetRootParentMenu(m_parentMenu)->m_accel;

    const size_t extraAccelsSize = m_extraAccels.size();
    for (size_t i = 0; i < extraAccelsSize; ++i)
    {
        GtkAccel(m_extraAccels[i]).Add(m_menuItem, accelGroup, GTK_ACCEL_MASK);
    }
}

void wxMenuItem::AddExtraAccel(const wxAcceleratorEntry& accel)
{
    wxMenuItemBase::AddExtraAccel(accel);

    // If the item is not yet part of the menu, all its extra accelerators will
    // be registered with GTK in GTKSetExtraAccels() once it is added to the
    // menu, but if it had already been added to it, we need to let GTK know
    // about the new extra accelerator.
    if (m_menuItem)
    {
        GtkAccelGroup* const accelGroup = GetRootParentMenu(m_parentMenu)->m_accel;

        GtkAccel(accel).Add(m_menuItem, accelGroup, GTK_ACCEL_MASK);
    }
}

void wxMenuItem::ClearExtraAccels()
{
    // Tell GTK not to use the existing accelerators any longer if they're
    // already in use.
    if (m_menuItem)
    {
        GtkAccelGroup* const accelGroup = GetRootParentMenu(m_parentMenu)->m_accel;

        const size_t extraAccelsSize = m_extraAccels.size();
        for (size_t i = 0; i < extraAccelsSize; ++i)
        {
            GtkAccel(m_extraAccels[i]).Remove(m_menuItem, accelGroup);
        }
    }

    wxMenuItemBase::ClearExtraAccels();
}

#endif // wxUSE_ACCEL

void wxMenuItem::SetupBitmaps(wxWindow *win)
{
#ifndef __WXGTK4__
    if ( m_menuItem && m_bitmap.IsOk() )
    {
        GtkWidget* image = wxGtkImage::New(win);
        WX_GTK_IMAGE(image)->Set(m_bitmap);
        gtk_widget_set_visible(image, TRUE);

        wxGCC_WARNING_SUPPRESS(deprecated-declarations)
        gtk_image_menu_item_set_image(GTK_IMAGE_MENU_ITEM(m_menuItem), image);
        wxGCC_WARNING_RESTORE(deprecated-declarations)
    }
#endif
}

void wxMenuItem::Check( bool check )
{
    wxCHECK_RET( m_menuItem, wxT("invalid menu item") );

    if (check == m_isChecked)
        return;

    switch ( GetKind() )
    {
        case wxITEM_RADIO:
            // It doesn't make sense to uncheck a radio item.
            if ( !check )
                return;

            wxFALLTHROUGH;
        case wxITEM_CHECK:
            wxMenuItemBase::Check( check );
            gtk_check_menu_item_set_active( (GtkCheckMenuItem*)m_menuItem, (gint)check );
            break;

        default:
            wxFAIL_MSG( wxT("can't check this item") );
    }
}

void wxMenuItem::Enable( bool enable )
{
    wxCHECK_RET( m_menuItem, wxT("invalid menu item") );

    gtk_widget_set_sensitive( m_menuItem, enable );
    wxMenuItemBase::Enable( enable );
}

bool wxMenuItem::IsChecked() const
{
    wxCHECK_MSG( m_menuItem, false, wxT("invalid menu item") );

    wxCHECK_MSG( IsCheckable(), false,
                 wxT("can't get state of uncheckable item!") );

    return gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(m_menuItem)) != 0;
}

#endif // __WXGTK4__/!__WXGTK4__

//-----------------------------------------------------------------------------
// wxMenu
//-----------------------------------------------------------------------------

#ifdef __WXGTK4__

void wxMenu::Init()
{
    m_popupShown = false;
    m_popover = nullptr;
    m_popupLoop = nullptr;
    m_enabledTop = true;

    m_menuModel = g_menu_new();
    m_actionGroup = g_simple_action_group_new();
    m_actionPrefix = wxString::Format("wxm%u", gs_menuSerial++);

    // An action which is never enabled, used for the entries GTK4 provides no
    // other way of disabling because they have no action of their own: sub
    // menu items, including the top level ones of a menu bar.
    GSimpleAction* const disabled =
        g_simple_action_new(wxGTK_DISABLED_ACTION, nullptr);
    g_simple_action_set_enabled(disabled, FALSE);
    g_action_map_add_action(G_ACTION_MAP(m_actionGroup), G_ACTION(disabled));
    g_object_unref(disabled);

    // Note that wxMENU_TEAROFF is silently ignored: tear-off menus were
    // implemented with GtkTearoffMenuItem, which is gone, and GTK4 has no
    // equivalent concept.

    // append the title as the very first entry if we have it
    if ( !m_title.empty() )
    {
        Append(wxGTK_TITLE_ID, m_title);
        AppendSeparator();
    }
}

wxMenu::~wxMenu()
{
    if ( m_popupLoop )
    {
        // We're being destroyed while popped up: don't leave GTKShowPopup()
        // spinning its nested main loop forever.
        g_main_loop_quit(m_popupLoop);
        m_popupLoop = nullptr;
    }

    if ( m_popover )
    {
        gtk_widget_unparent(m_popover);
        m_popover = nullptr;
    }

    g_object_unref(m_menuModel);
    g_object_unref(m_actionGroup);
}

void wxMenu::GTKRebuildModel()
{
    // Everything is regenerated rather than patched: GMenu copies a GMenuItem's
    // attributes when the item is inserted, so nothing can be updated in
    // place, and separators are modelled as sections, so wx item positions
    // don't correspond to model positions either. See the design document.
    g_menu_remove_all(m_menuModel);

    gchar** const names = g_action_group_list_actions(G_ACTION_GROUP(m_actionGroup));
    for ( gchar** p = names; *p; ++p )
    {
        if ( strcmp(*p, wxGTK_DISABLED_ACTION) != 0 )
            g_action_map_remove_action(G_ACTION_MAP(m_actionGroup), *p);
    }
    g_strfreev(names);

    const wxString disabledAction =
        m_actionPrefix + "." + wxGTK_DISABLED_ACTION;

    // Items between two separators form a section, which is how GTK4 draws
    // separators between them.
    GMenu* section = g_menu_new();

    // wx puts consecutive radio items into the same group and GTK4 needs a
    // single stateful action shared by the whole group, with each member
    // identified by its own target value.
    wxString radioAction;
    int radioIndex = 0;

    for ( wxMenuItemList::compatibility_iterator node = m_items.GetFirst();
          node;
          node = node->GetNext() )
    {
        wxMenuItem* const item = node->GetData();

        bool isFirstInRadioGroup = false;

        if ( item->GetKind() != wxITEM_RADIO )
            radioAction.clear();

        if ( item->IsSeparator() )
        {
            g_menu_append_section(m_menuModel, nullptr, G_MENU_MODEL(section));
            g_object_unref(section);
            section = g_menu_new();
            continue;
        }

        // GTK4 shows the accelerator from the item's "accel" attribute, so it
        // must not be part of the label.
        const wxString label(
            wxConvertMnemonicsToGTK(item->GetItemLabel().BeforeFirst('\t')));

        GMenuItem* gitem;

        if ( item->IsSubMenu() && item->IsEnabled() )
        {
            gitem = g_menu_item_new_submenu(
                        label.utf8_str(),
                        G_MENU_MODEL(item->GetSubMenu()->GTKGetMenuModel()));

            item->GTKSetActionName(wxString());
            item->GTKSetRadioTarget(wxString());
        }
        else if ( item->IsSubMenu() )
        {
            // See wxMenuItem::Enable(): a disabled sub menu becomes a plain,
            // permanently disabled item with the same label.
            gitem = g_menu_item_new(label.utf8_str(), nullptr);
            g_menu_item_set_detailed_action(gitem, disabledAction.utf8_str());

            item->GTKSetActionName(wxString());
            item->GTKSetRadioTarget(wxString());
        }
        else
        {
            wxString actionName;
            wxString target;

            switch ( item->GetKind() )
            {
                case wxITEM_CHECK:
                    actionName = wxString::Format("i%u", gs_actionSerial++);
                    {
                        GSimpleAction* const action =
                            g_simple_action_new_stateful(
                                actionName.utf8_str(), nullptr,
                                g_variant_new_boolean(
                                    item->wxMenuItemBase::IsChecked()));
                        g_signal_connect(action, "change-state",
                                         G_CALLBACK(wx_menu_check_state), item);
                        g_action_map_add_action(G_ACTION_MAP(m_actionGroup),
                                                G_ACTION(action));
                        g_object_unref(action);
                    }
                    break;

                case wxITEM_RADIO:
                    if ( radioAction.empty() )
                    {
                        radioAction = wxString::Format("r%u", gs_actionSerial++);
                        radioIndex = 0;

                        GSimpleAction* const action =
                            g_simple_action_new_stateful(
                                radioAction.utf8_str(), G_VARIANT_TYPE_STRING,
                                g_variant_new_string(""));
                        g_signal_connect(action, "change-state",
                                         G_CALLBACK(wx_menu_radio_state), this);
                        g_action_map_add_action(G_ACTION_MAP(m_actionGroup),
                                                G_ACTION(action));
                        g_object_unref(action);
                    }

                    actionName = radioAction;
                    isFirstInRadioGroup = radioIndex == 0;
                    target = wxString::Format("%d", radioIndex++);
                    break;

                default:
                    wxFAIL_MSG("unexpected menu item kind");
                    wxFALLTHROUGH;

                case wxITEM_NORMAL:
                    actionName = wxString::Format("i%u", gs_actionSerial++);
                    {
                        GSimpleAction* const action =
                            g_simple_action_new(actionName.utf8_str(), nullptr);
                        g_signal_connect(action, "activate",
                                         G_CALLBACK(wx_menu_item_activate), item);
                        g_action_map_add_action(G_ACTION_MAP(m_actionGroup),
                                                G_ACTION(action));
                        g_object_unref(action);
                    }
                    break;
            }

            item->GTKSetActionName(actionName);
            item->GTKSetRadioTarget(target);

            GSimpleAction* const action = FindItemAction(item);

            // The first item of a radio group is checked by default, as
            // GTK3's GtkRadioMenuItem made it and as wx documents. Nothing
            // does that for a GAction: a group is just a stateful action whose
            // state happens to match one member's target, and it starts out
            // matching none of them. Items are visited in order, so a member
            // which really is checked simply overwrites this below.
            if ( item->GetKind() == wxITEM_RADIO &&
                    (isFirstInRadioGroup || item->wxMenuItemBase::IsChecked()) )
            {
                g_simple_action_set_state(
                    action, g_variant_new_string(target.utf8_str()));
            }

            if ( !item->IsEnabled() )
                g_simple_action_set_enabled(action, FALSE);

            gitem = g_menu_item_new(label.utf8_str(), nullptr);

            const wxString fullName = m_actionPrefix + "." + actionName;
            if ( target.empty() )
            {
                g_menu_item_set_detailed_action(gitem, fullName.utf8_str());
            }
            else
            {
                // An item with a target and an action with state is what makes
                // GTK4 draw the item as a radio rather than as a check.
                g_menu_item_set_action_and_target_value(
                    gitem, fullName.utf8_str(),
                    g_variant_new_string(target.utf8_str()));
            }

#if wxUSE_ACCEL
            const GtkAccel accel(item);
            if ( accel.IsOk() )
            {
                wxGtkString name(gtk_accelerator_name(accel.GetKey(),
                                                      accel.GetMods()));
                g_menu_item_set_attribute(gitem, "accel", "s", name.c_str());
            }
#endif // wxUSE_ACCEL

            if ( GIcon* const icon = MakeMenuIcon(item->GetBitmapBundle(),
                                                  item->GTKGetBitmapWindow()) )
            {
                g_menu_item_set_icon(gitem, icon);
                g_object_unref(icon);
            }
        }

        g_menu_append_item(section, gitem);
        g_object_unref(gitem);
    }

    g_menu_append_section(m_menuModel, nullptr, G_MENU_MODEL(section));
    g_object_unref(section);

    GTKRefreshShortcuts();
}

void wxMenu::GTKRefreshShortcuts()
{
    // Only the menu bar knows the widget the shortcuts are installed on, and
    // it registers them for all the items of all its menus at once.
    if ( wxMenuBar* const menubar = GetRootParentMenu(this)->GetMenuBar() )
        menubar->GTKRebuildModel();
}

void wxMenu::GTKInstallActions(GtkWidget* widget)
{
    gtk_widget_insert_action_group(widget, m_actionPrefix.utf8_str(),
                                   G_ACTION_GROUP(m_actionGroup));

    for ( auto* item : m_items )
    {
        if ( wxMenu* const submenu = item->GetSubMenu() )
            submenu->GTKInstallActions(widget);
    }
}

void wxMenu::GTKUninstallActions(GtkWidget* widget)
{
    gtk_widget_insert_action_group(widget, m_actionPrefix.utf8_str(), nullptr);

    for ( auto* item : m_items )
    {
        if ( wxMenu* const submenu = item->GetSubMenu() )
            submenu->GTKUninstallActions(widget);
    }
}

namespace
{

// What a menu accelerator needs to know at the moment its key is pressed.
// GtkShortcutFunc is not given the event, so the trigger is remembered here
// alongside the action to activate.
struct wxMenuShortcut
{
    wxMenuShortcut(const wxString& action, int key, int mods)
        : m_action(action.utf8_str()), m_key(key), m_mods(mods)
    {
    }

    const wxCharBuffer m_action;
    const int m_key;
    const int m_mods;
};

void wx_menu_shortcut_free(gpointer data)
{
    delete static_cast<wxMenuShortcut*>(data);
}

// Run the menu item's action, unless the focused window binds this key for
// itself: GTK4 runs a window shortcut whatever the focused widget does with
// the key, in every scope it offers, so this is the only place the two can be
// told apart. See #221.
gboolean
wx_menu_shortcut_activate(GtkWidget* widget, GVariant* args, gpointer data)
{
    const wxMenuShortcut* const shortcut = static_cast<wxMenuShortcut*>(data);

    if ( wxWindow* const focus = wxWindow::FindFocus() )
    {
        if ( focus->GTKShouldPreProcessKey(shortcut->m_key, shortcut->m_mods) )
            return FALSE;
    }

    return gtk_widget_activate_action_variant(widget, shortcut->m_action, args);
}

} // anonymous namespace

void wxMenu::GTKAddShortcuts(GtkShortcutController* controller)
{
#if wxUSE_ACCEL
    for ( auto* item : m_items )
    {
        if ( wxMenu* const submenu = item->GetSubMenu() )
        {
            submenu->GTKAddShortcuts(controller);
            continue;
        }

        if ( item->GTKGetActionName().empty() )
            continue;

        const wxString fullName = m_actionPrefix + "." + item->GTKGetActionName();
        const wxString& target = item->GTKGetRadioTarget();

        // Collect the item's own accelerator, if any, and all its extra ones.
        wxVector<GtkAccel> accels;

        const GtkAccel accel(item);
        if ( accel.IsOk() )
            accels.push_back(accel);

        for ( const auto& extra : item->GetExtraAccels() )
        {
            const GtkAccel extraAccel(extra);
            if ( extraAccel.IsOk() )
                accels.push_back(extraAccel);
        }

        for ( const auto& a : accels )
        {
            GtkShortcut* const shortcut =
                gtk_shortcut_new(gtk_keyval_trigger_new(a.GetKey(), a.GetMods()),
                                 gtk_callback_action_new(
                                     wx_menu_shortcut_activate,
                                     new wxMenuShortcut(fullName,
                                                        a.GetKey(),
                                                        a.GetMods()),
                                     wx_menu_shortcut_free));

            if ( !target.empty() )
            {
                gtk_shortcut_set_arguments(
                    shortcut, g_variant_new_string(target.utf8_str()));
            }

            gtk_shortcut_controller_add_shortcut(controller, shortcut);
        }
    }
#else // !wxUSE_ACCEL
    wxUnusedVar(controller);
#endif // wxUSE_ACCEL/!wxUSE_ACCEL
}

void wxMenu::GTKOnRadioSelected(const char* actionName, const wxString& target)
{
    // GTK only tells us which item of the group is selected now, so update the
    // state of the whole group before sending the event for the new selection.
    const wxString name = wxString::FromUTF8(actionName);

    wxMenuItem* selected = nullptr;
    for ( auto* item : m_items )
    {
        if ( item->GetKind() != wxITEM_RADIO ||
                item->GTKGetActionName() != name )
            continue;

        const bool isThisOne = item->GTKGetRadioTarget() == target;
        item->wxMenuItemBase::Check(isThisOne);
        if ( isThisOne )
            selected = item;
    }

    if ( selected )
        ActivateMenuItem(selected, 1);
}

bool wxMenu::GTKShowPopup(wxWindow* win, int x, int y)
{
    wxCHECK_MSG( win, false, wxT("no window to show the popup menu over") );

    GtkWidget* const parent = win->m_wxwindow ? win->m_wxwindow : win->m_widget;
    wxCHECK_MSG( parent, false, wxT("invalid window") );

    SetupBitmaps(win);
    GTKInstallActions(parent);

    m_popover = gtk_popover_menu_new_from_model(G_MENU_MODEL(m_menuModel));
    gtk_widget_set_parent(m_popover, parent);
    gtk_popover_set_has_arrow(GTK_POPOVER(m_popover), FALSE);
    gtk_widget_set_halign(m_popover, GTK_ALIGN_START);

    if ( x == -1 && y == -1 )
    {
        const wxPoint pt = win->ScreenToClient(wxGetMousePosition());
        x = pt.x;
        y = pt.y;
    }

    const GdkRectangle rect = { x, y, 1, 1 };
    gtk_popover_set_pointing_to(GTK_POPOVER(m_popover), &rect);

    PopupData data;
    data.menu = this;
    data.loop = g_main_loop_new(nullptr, FALSE);

    m_popupLoop = data.loop;
    m_popupShown = true;

    g_signal_connect(m_popover, "show",
                     G_CALLBACK(wx_menu_popover_show), &data);
    g_signal_connect(m_popover, "closed",
                     G_CALLBACK(wx_menu_popover_closed), &data);

    gtk_popover_popup(GTK_POPOVER(m_popover));

    // wxWindow::PopupMenu() is documented to return only once the menu has
    // been dismissed, but GTK4 popovers are not modal in the sense GtkMenu
    // was, so run a nested main loop, as we do for modal dialogs.
    g_main_loop_run(data.loop);

    m_popupShown = false;
    m_popupLoop = nullptr;
    g_main_loop_unref(data.loop);

    if ( m_popover )
    {
        g_signal_handlers_disconnect_by_data(m_popover, &data);
        gtk_widget_unparent(m_popover);
        m_popover = nullptr;
    }

    wxMenuEvent event(wxEVT_MENU_CLOSE, -1, this);
    DoCommonMenuCallbackCode(this, event);

    GTKUninstallActions(parent);

    return true;
}

void wxMenu::SetLayoutDirection(wxLayoutDirection dir)
{
    // There are no per-item widgets under GTK4 to set the direction on: it is
    // set on the menu bar or popover widget and inherited from there.
    wxUnusedVar(dir);
}

wxLayoutDirection wxMenu::GetLayoutDirection() const
{
    return wxLayout_Default;
}

#else // !__WXGTK4__

extern "C" {
// "map" from m_menu
static void menu_map(GtkWidget*, wxMenu* menu)
{
    wxMenuEvent event(wxEVT_MENU_OPEN, menu->m_popupShown ? -1 : 0, menu);
    DoCommonMenuCallbackCode(menu, event);
}

// "hide" from m_menu
static void menu_hide(GtkWidget*, wxMenu* menu)
{
    // When using Ubuntu Unity desktop environment we get "hide" signal even
    // when the window is not shown yet because Unity hides all the menus to
    // show them only in the global menu bar. Just ignore this even instead of
    // crashing in DoCommonMenuCallbackCode().
    if ( !menu->GetWindow() )
        return;

    wxMenuEvent event(wxEVT_MENU_CLOSE, menu->m_popupShown ? -1 : 0, menu);
    menu->m_popupShown = false;
    DoCommonMenuCallbackCode(menu, event);
}
}

// "can_activate_accel" from menu item
extern "C" {
static gboolean can_activate_accel(GtkWidget*, guint, wxMenu* menu)
{
    menu->UpdateUI();
    // always allow our "activate" handler to be called
    return true;
}
}

void wxMenu::Init()
{
    m_popupShown = false;

    m_accel = gtk_accel_group_new();
    m_menu = gtk_menu_new();
    g_object_ref_sink(m_menu);

    m_owner = nullptr;

#ifndef __WXGTK4__
    // Tearoffs are entries, just like separators. So if we want this
    // menu to be a tear-off one, we just append a tearoff entry
    // immediately.
    if ( m_style & wxMENU_TEAROFF )
    {
        wxGCC_WARNING_SUPPRESS(deprecated-declarations)
        GtkWidget *tearoff = gtk_tearoff_menu_item_new();
        wxGCC_WARNING_RESTORE()

        gtk_menu_shell_append(GTK_MENU_SHELL(m_menu), tearoff);
    }
#endif

    // append the title as the very first entry if we have it
    if ( !m_title.empty() )
    {
        Append(wxGTK_TITLE_ID, m_title);
        AppendSeparator();
    }

    // "show" occurs for sub-menus which are not showing, so use "map" instead
    g_signal_connect(m_menu, "map", G_CALLBACK(menu_map), this);
    g_signal_connect(m_menu, "hide", G_CALLBACK(menu_hide), this);
}

wxMenu::~wxMenu()
{
    // Destroying a menu generates a "hide" signal even if it's not shown
    // currently, so disconnect it to avoid dummy wxEVT_MENU_CLOSE events
    // generation.
    g_signal_handlers_disconnect_by_data(m_menu, this);

    if (m_owner)
    {
        gtk_widget_destroy(m_owner);
        g_object_unref(m_owner);
    }
    else
        gtk_widget_destroy(m_menu);

    g_object_unref(m_menu);
    g_object_unref(m_accel);
}

void wxMenu::SetLayoutDirection(wxLayoutDirection dir)
{
    if ( m_owner )
    {
        wxWindow::GTKSetLayout(m_owner, dir);

        wxMenuItemList::compatibility_iterator node = m_items.GetFirst();
        for (; node; node = node->GetNext())
        {
            wxMenuItem* item = node->GetData();
            if (wxMenu* subMenu = item->GetSubMenu())
                subMenu->SetLayoutDirection(dir);
            else if (GtkWidget* widget = item->GetMenuItem())
            {
                wxWindow::GTKSetLayout(widget, dir);
                widget = gtk_bin_get_child(GTK_BIN(widget));
                if (widget)
                    wxWindow::GTKSetLayout(widget, dir);
            }
        }
    }
    //else: will be called later by wxMenuBar again
}

wxLayoutDirection wxMenu::GetLayoutDirection() const
{
    return wxWindow::GTKGetLayout(m_owner);
}

#endif // __WXGTK4__/!__WXGTK4__

wxString wxMenu::GetTitle() const
{
    return wxConvertMnemonicsFromGTK(wxMenuBase::GetTitle());
}

void wxMenu::SetTitle(const wxString& title)
{
    wxMenuBase::SetTitle(wxConvertMnemonicsToGTK(title));
}

#ifdef __WXGTK4__

void wxMenu::GtkAppend(wxMenuItem* mitem, int pos)
{
    // Neither is used: the model is regenerated from the item list, which the
    // base class has already updated for us.
    wxUnusedVar(mitem);
    wxUnusedVar(pos);

    GTKRebuildModel();
}

#else // !__WXGTK4__

void wxMenu::GtkAppend(wxMenuItem* mitem, int pos)
{
    GtkWidget *menuItem;
    switch (mitem->GetKind())
    {
        case wxITEM_SEPARATOR:
            menuItem = gtk_separator_menu_item_new();
            break;
        case wxITEM_CHECK:
            menuItem = gtk_check_menu_item_new_with_label("");
            break;
        case wxITEM_RADIO:
            {
                // See if we need to create a new radio group for this item or
                // add it to an existing one.
                wxMenuItem* radioGroupItem = nullptr;

                const size_t numItems = GetMenuItemCount();
                const size_t n = pos == -1 ? numItems - 1 : size_t(pos);

                if (n != 0)
                {
                    wxMenuItem* const itemPrev = FindItemByPosition(n - 1);
                    if ( itemPrev->GetKind() == wxITEM_RADIO )
                    {
                        // Appending an item after an existing radio item puts
                        // it into the same radio group.
                        radioGroupItem = itemPrev;
                    }
                }

                if (radioGroupItem == nullptr && n != numItems - 1)
                {
                    wxMenuItem* const itemNext = FindItemByPosition(n + 1);
                    if ( itemNext->GetKind() == wxITEM_RADIO )
                    {
                        // Inserting an item before an existing radio item
                        // also puts it into the existing radio group.
                        radioGroupItem = itemNext;
                    }
                }

                GSList* group = nullptr;
                if ( radioGroupItem )
                {
                    group = gtk_radio_menu_item_get_group(
                              GTK_RADIO_MENU_ITEM(radioGroupItem->GetMenuItem())
                            );
                }

                menuItem = gtk_radio_menu_item_new_with_label(group, "");
            }
            break;
        default:
            wxFAIL_MSG("unexpected menu item kind");
            wxFALLTHROUGH;
        case wxITEM_NORMAL:
#ifdef __WXGTK4__
            //TODO GtkImageMenuItem is gone, have to implement it ourselves with
            //   GtkMenuItem GtkBox GtkAccelLabel GtkImage
            menuItem = gtk_menu_item_new_with_label("");
#else
            wxGCC_WARNING_SUPPRESS(deprecated-declarations)
            if (mitem->GetBitmap().IsOk())
            {
                menuItem = gtk_image_menu_item_new_with_label("");
            }
            else
            {
                const char* stockid = wxGetStockGtkID(mitem->GetId());
                if (stockid)
                    // use stock bitmap for this item if available on the assumption
                    // that it never hurts to follow GTK+ conventions more closely
                    menuItem = gtk_image_menu_item_new_from_stock(stockid, nullptr);
                else
                    // Even though no bitmap is set yet, still create an
                    // image-capable item: SetBitmap() is commonly called
                    // after Append() returns (Append() returns the new
                    // wxMenuItem* precisely to support this), and
                    // SetupBitmaps() later calls
                    // gtk_image_menu_item_set_image(), which requires the
                    // underlying widget to already be a GtkImageMenuItem.
                    // A GtkImageMenuItem with no image behaves the same as
                    // a plain GtkMenuItem, so this is harmless when no
                    // bitmap is ever set.
                    menuItem = gtk_image_menu_item_new_with_label("");
            }
            wxGCC_WARNING_RESTORE()
#endif
            break;
    }
    mitem->SetMenuItem(menuItem);

    gtk_menu_shell_insert(GTK_MENU_SHELL(m_menu), menuItem, pos);

    gtk_widget_set_visible(menuItem, TRUE);

    if ( !mitem->IsSeparator() )
    {
        mitem->SetGtkLabel();
        if ( mitem->IsSubMenu() )
            UpdateSubMenuItemLabels(mitem);

#if wxUSE_ACCEL
        mitem->GTKSetExtraAccels();
#endif

        g_signal_connect (menuItem, "select",
                          G_CALLBACK(menuitem_select), mitem);
        g_signal_connect (menuItem, "deselect",
                          G_CALLBACK(menuitem_deselect), mitem);

        if ( mitem->IsSubMenu() && mitem->GetKind() != wxITEM_RADIO && mitem->GetKind() != wxITEM_CHECK )
        {
            gtk_menu_item_set_submenu( GTK_MENU_ITEM(menuItem), mitem->GetSubMenu()->m_menu );

            gtk_widget_set_visible(mitem->GetSubMenu()->m_menu, TRUE);
        }
        else
        {
            g_signal_connect(menuItem, "can_activate_accel",
                G_CALLBACK(can_activate_accel), this);
            g_signal_connect (menuItem, "activate",
                              G_CALLBACK(menuitem_activate),
                              mitem);
        }
    }
}

#endif // __WXGTK4__/!__WXGTK4__

wxMenuItem* wxMenu::DoAppend(wxMenuItem *mitem)
{
    if (wxMenuBase::DoAppend(mitem))
    {
        GtkAppend(mitem);
        return mitem;
    }
    return nullptr;
}

wxMenuItem* wxMenu::DoInsert(size_t pos, wxMenuItem *item)
{
    if (wxMenuBase::DoInsert(pos, item))
    {
        GtkAppend(item, int(pos));
        return item;
    }
    return nullptr;
}

#ifdef __WXGTK4__

wxMenuItem *wxMenu::DoRemove(wxMenuItem *item)
{
    if ( !wxMenuBase::DoRemove(item) )
        return nullptr;

    // The item's action is dropped by the rebuild below, so make sure the item
    // doesn't keep referring to it.
    item->GTKSetActionName(wxString());
    item->GTKSetRadioTarget(wxString());

    GTKRebuildModel();

    return item;
}

#else // !__WXGTK4__

wxMenuItem *wxMenu::DoRemove(wxMenuItem *item)
{
    if ( !wxMenuBase::DoRemove(item) )
        return nullptr;

    GtkWidget * const mitem = item->GetMenuItem();

    g_signal_handlers_disconnect_by_data(mitem, item);

#ifdef __WXGTK3__
    gtk_menu_item_set_submenu(GTK_MENU_ITEM(mitem), nullptr);
#else
    gtk_menu_item_remove_submenu(GTK_MENU_ITEM(mitem));
#endif

    gtk_widget_destroy(mitem);
    item->SetMenuItem(nullptr);

    return item;
}

#endif // __WXGTK4__/!__WXGTK4__

void wxMenu::Attach(wxMenuBarBase *menubar)
{
    wxMenuBase::Attach(menubar);

    // inherit layout direction from menubar.
    SetLayoutDirection(menubar->GetLayoutDirection());
}

void wxMenu::SetupBitmaps(wxWindow *win)
{
#ifdef __WXGTK4__
    // Under GTK4 the item bitmaps are icon attributes of the menu model, so
    // they can only be updated by regenerating it -- but only do this if there
    // is at least one bitmap to show, as this function is called for every
    // menu whenever a menu bar is attached to a frame.
    bool anyBitmap = false;
#endif // __WXGTK4__

    wxMenuItemList::compatibility_iterator node = GetMenuItems().GetFirst();
    while (node)
    {
        wxMenuItem *menuitem = node->GetData();
        if (menuitem->IsSubMenu())
            menuitem->GetSubMenu()->SetupBitmaps(win);
        if (!menuitem->IsSeparator())
        {
            menuitem->SetupBitmaps(win);
#ifdef __WXGTK4__
            if ( menuitem->GetBitmapBundle().IsOk() )
                anyBitmap = true;
#endif // __WXGTK4__
        }
        node = node->GetNext();
    }

#ifdef __WXGTK4__
    if ( anyBitmap )
        GTKRebuildModel();
#endif // __WXGTK4__
}

// ----------------------------------------------------------------------------
// helpers
// ----------------------------------------------------------------------------

#if wxUSE_ACCEL

/* static */
wxString GtkAccel::GetGtkHotKey(const wxAcceleratorEntry *accel)
{
    wxString hotkey;

    if ( accel )
    {
        int flags = accel->GetFlags();
        if ( flags & wxACCEL_ALT )
            hotkey += wxT("<alt>");
        if ( flags & wxACCEL_CTRL )
            hotkey += wxT("<control>");
        if ( flags & wxACCEL_SHIFT )
            hotkey += wxT("<shift>");

        // Accelerator can be invalid for 2 different reasons from GTK point of
        // view: either the key just can't be used as an accelerator at all
        // (e.g. TAB), or it can only be used as an accelerator with modifiers.
        // This variable can be set to one of the matching values in the switch
        // below and is used to give the most fitting error message later.
        enum Validity
        {
            Valid_Always,
            Valid_Never,
            Valid_WithModifiers
        } validity = Valid_Always;

        int code = accel->GetKeyCode();
        switch ( code )
        {
            case WXK_F1:  case WXK_F2:  case WXK_F3:  case WXK_F4:  case WXK_F5:
            case WXK_F6:  case WXK_F7:  case WXK_F8:  case WXK_F9:  case WXK_F10:
            case WXK_F11: case WXK_F12: case WXK_F13: case WXK_F14: case WXK_F15:
            case WXK_F16: case WXK_F17: case WXK_F18: case WXK_F19: case WXK_F20:
            case WXK_F21: case WXK_F22: case WXK_F23: case WXK_F24:
                hotkey += wxString::Format(wxT("F%d"), code - WXK_F1 + 1);
                break;

                // TODO: we should use gdk_keyval_name() (a.k.a.
                //       XKeysymToString) here as well as hardcoding the keysym
                //       names this might be not portable
            case WXK_INSERT:
                hotkey << wxT("Insert" );
                break;
            case WXK_DELETE:
                hotkey << wxT("Delete" );
                break;
            case WXK_UP:
                validity = Valid_WithModifiers;
                hotkey << wxT("Up" );
                break;
            case WXK_DOWN:
                validity = Valid_WithModifiers;
                hotkey << wxT("Down" );
                break;
            case WXK_LEFT:
                validity = Valid_WithModifiers;
                hotkey << wxT("Left" );
                break;
            case WXK_RIGHT:
                validity = Valid_WithModifiers;
                hotkey << wxT("Right" );
                break;
            case WXK_PAGEUP:
                hotkey << wxT("Page_Up" );
                break;
            case WXK_PAGEDOWN:
                hotkey << wxT("Page_Down" );
                break;
            case WXK_HOME:
                hotkey << wxT("Home" );
                break;
            case WXK_END:
                hotkey << wxT("End" );
                break;
            case WXK_RETURN:
                hotkey << wxT("Return" );
                break;
            case WXK_BACK:
                hotkey << wxT("BackSpace" );
                break;
            case WXK_ESCAPE:
                hotkey << wxT("Escape" );
                break;
            case WXK_SPACE:
                hotkey << wxT("space" );
                break;
            case WXK_MULTIPLY:
                hotkey << wxT("multiply" );
                break;
            case WXK_CANCEL:
                hotkey << wxT("Cancel" );
                break;
            case WXK_CLEAR:
                hotkey << wxT("Clear" );
                break;
            case WXK_MENU:
                hotkey << wxT("Menu" );
                break;
            case WXK_PAUSE:
                hotkey << wxT("Pause" );
                break;
            case WXK_SELECT:
                hotkey << wxT("Select" );
                break;
            case WXK_PRINT:
                hotkey << wxT("Print" );
                break;
            case WXK_EXECUTE:
                hotkey << wxT("Execute" );
                break;
            case WXK_HELP:
                hotkey << wxT("Help" );
                break;
            case WXK_NUMPAD_INSERT:
                hotkey << wxT("KP_Insert" );
                break;
            case WXK_NUMPAD_DELETE:
                hotkey << wxT("KP_Delete" );
                break;
             case WXK_NUMPAD_SPACE:
                hotkey << wxT("KP_Space" );
                break;
            case WXK_NUMPAD_ENTER:
                hotkey << wxT("KP_Enter" );
                break;
            case WXK_NUMPAD_F1: case WXK_NUMPAD_F2: case WXK_NUMPAD_F3:
            case WXK_NUMPAD_F4:
                hotkey += wxString::Format(wxT("KP_F%d"), code - WXK_NUMPAD_F1 + 1);
                break;
            case WXK_NUMPAD_HOME:
                hotkey << wxT("KP_Home" );
                break;
             case WXK_NUMPAD_UP:
                validity = Valid_WithModifiers;
                hotkey << wxT("KP_Up" );
                break;
            case WXK_NUMPAD_DOWN:
                validity = Valid_WithModifiers;
                hotkey << wxT("KP_Down" );
                break;
            case WXK_NUMPAD_LEFT:
                validity = Valid_WithModifiers;
                hotkey << wxT("KP_Left" );
                break;
            case WXK_NUMPAD_RIGHT:
                validity = Valid_WithModifiers;
                hotkey << wxT("KP_Right" );
                break;
            case WXK_NUMPAD_PAGEUP:
                hotkey << wxT("KP_Page_Up" );
                break;
            case WXK_NUMPAD_PAGEDOWN:
                hotkey << wxT("KP_Page_Down" );
                break;
            case WXK_NUMPAD_END:
                hotkey << wxT("KP_End" );
                break;
            case WXK_NUMPAD_BEGIN:
                hotkey << wxT("KP_Begin" );
                break;
            case WXK_NUMPAD_EQUAL:
                hotkey << wxT("KP_Equal" );
                break;
            case WXK_NUMPAD_MULTIPLY:
                hotkey << wxT("KP_Multiply" );
                break;
            case WXK_NUMPAD_ADD:
                hotkey << wxT("KP_Add" );
                break;
            case WXK_NUMPAD_SEPARATOR:
                hotkey << wxT("KP_Separator" );
                break;
            case WXK_NUMPAD_SUBTRACT:
                hotkey << wxT("KP_Subtract" );
                break;
            case WXK_NUMPAD_DECIMAL:
                hotkey << wxT("KP_Decimal" );
                break;
            case WXK_NUMPAD_DIVIDE:
                hotkey << wxT("KP_Divide" );
                break;
           case WXK_NUMPAD0: case WXK_NUMPAD1: case WXK_NUMPAD2:
           case WXK_NUMPAD3: case WXK_NUMPAD4: case WXK_NUMPAD5:
           case WXK_NUMPAD6: case WXK_NUMPAD7: case WXK_NUMPAD8:
           case WXK_NUMPAD9:
                hotkey += wxString::Format(wxT("KP_%d"), code - WXK_NUMPAD0);
                break;
            case WXK_WINDOWS_MENU:
                hotkey << wxT("Menu" );
                break;

            /*
             The following keycodes have been shown not to work as accelerator
             keys on GTK (see https://github.com/wxWidgets/wxWidgets/issues/10049)
             and are not valid
             (see gtkaccelgroup.c inside gtk_accelerator_valid())
             */
            case WXK_COMMAND:   // Same as WXK_CONTROL
            case WXK_SHIFT:
            case WXK_ALT:
            case WXK_SCROLL:    // Scroll lock
            case WXK_CAPITAL:   // Caps lock
            case WXK_NUMLOCK:
            case WXK_NUMPAD_TAB:
            case WXK_TAB:
            case WXK_WINDOWS_LEFT:
            case WXK_WINDOWS_RIGHT:

            /*
             The following keycodes do not map clearly into a GTK keycode,
             so they are not included in the accelerator mapping:
             */
            case WXK_ADD:
            case WXK_SEPARATOR:
            case WXK_SUBTRACT:
            case WXK_DECIMAL:
            case WXK_DIVIDE:
            case WXK_SNAPSHOT:

            /*
             The following special codes do not map into GTK keycodes,
             see gdk/keynames.txt
             */
            case WXK_SPECIAL1:  case WXK_SPECIAL2:  case WXK_SPECIAL3:
            case WXK_SPECIAL4:  case WXK_SPECIAL5:  case WXK_SPECIAL6:
            case WXK_SPECIAL7:  case WXK_SPECIAL8:  case WXK_SPECIAL9:
            case WXK_SPECIAL10: case WXK_SPECIAL11: case WXK_SPECIAL12:
            case WXK_SPECIAL13: case WXK_SPECIAL14: case WXK_SPECIAL15:
            case WXK_SPECIAL16: case WXK_SPECIAL17: case WXK_SPECIAL18:
            case WXK_SPECIAL19: case WXK_SPECIAL20:
                validity = Valid_Never;
                break;

            // if there are any other keys wxAcceleratorEntry::Create() may
            // return, we should process them here

            default:
                if ( code < 127 )
                {
                    const wxString
                        name = wxString::FromUTF8(gdk_keyval_name((guint)code));
                    if ( !name.empty() )
                    {
                        hotkey << name;
                        break;
                    }
                }

                wxLogDebug( "Unknown keyboard accelerator key code: %i", code );
                hotkey.clear();
        }

        switch ( validity )
        {
            case Valid_Always:
                break;

            case Valid_Never:
                wxLogDebug("\"%s\" is not supported as "
                           "a keyboard accelerator with GTK",
                           accel->ToString());
                hotkey.clear();
                break;

            case Valid_WithModifiers:
                if ( !flags )
                {
                    wxLogDebug("\"%s\" must use modifiers to be used as "
                               "a keyboard accelerator with GTK",
                               accel->ToString());
                    hotkey.clear();
                }
                break;
        }
    }

    return hotkey;
}

void GtkAccel::Init(const wxAcceleratorEntry* entry)
{
    const wxString string = GetGtkHotKey(entry);
    if (!string.empty())
    {
        gtk_accelerator_parse(string.utf8_str(), &m_key, &m_mods);

        // Normally, we detect all the keys considered invalid by GTK in
        // GetGtkHotKey(), but just in case GTK decides to add more invalid
        // keys in the future versions, recheck once again using its function.
        if ( !gtk_accelerator_valid(m_key, m_mods) )
        {
            wxLogDebug("\"%s\" is not a valid keyboard accelerator "
                       "for this GTK version",
                       string);
            m_key = 0;
        }
    }
    else
    {
        // Key with this code can never be a valid accelerator, so we use
        // it to indicate that it's invalid.
        m_key = 0;
    }
}

GtkAccel::GtkAccel(const wxMenuItem* item)
{
    std::unique_ptr<wxAcceleratorEntry> accel(item->GetAccel());
    Init(accel.get());

#ifndef __WXGTK4__
    if ( !IsOk() )
    {
        wxGCC_WARNING_SUPPRESS(deprecated-declarations)

        // Check if this is a stock item for which GTK defines a default
        // accelerator.
        GtkStockItem stock_item;
        const char* stockid = wxGetStockGtkID(item->GetId());
        if ( stockid &&
                gtk_stock_lookup(stockid, &stock_item) &&
                    stock_item.keyval )
        {
            m_key = stock_item.keyval;
            m_mods = stock_item.modifier;
        }
        wxGCC_WARNING_RESTORE()
    }
#endif // !__WXGTK4__
}

#ifndef __WXGTK4__

void
GtkAccel::Add(GtkWidget* widget, GtkAccelGroup* accelGroup, GtkAccelFlags accelFlags)
{
    if ( IsOk() )
    {
        gtk_widget_add_accelerator(
            widget, "activate", accelGroup,
            m_key, m_mods, accelFlags);
    }
}

void GtkAccel::Remove(GtkWidget* widget, GtkAccelGroup* accelGroup)
{
    if ( IsOk() )
    {
        gtk_widget_remove_accelerator(widget, accelGroup, m_key, m_mods);
    }
}

#endif // !__WXGTK4__

#endif // wxUSE_ACCEL

#ifndef __WXGTK4__
wxGCC_WARNING_SUPPRESS(deprecated-declarations)
wxGCC_WARNING_SUPPRESS(cast-qual)
const char *wxGetStockGtkID(wxWindowID id)
{
    #define STOCKITEM(wx,gtk)      \
        case wx:                   \
            return gtk;

    #if GTK_CHECK_VERSION(2,8,0)
        #define STOCKITEM_28(wx,gtk) STOCKITEM(wx,gtk)
    #else
        #define STOCKITEM_28(wx,gtk)
    #endif

    #if GTK_CHECK_VERSION(2,10,0)
        #define STOCKITEM_210(wx,gtk) STOCKITEM(wx,gtk)
    #else
        #define STOCKITEM_210(wx,gtk)
    #endif


    switch (id)
    {
        STOCKITEM(wxID_ABOUT,            GTK_STOCK_ABOUT)
        STOCKITEM(wxID_ADD,              GTK_STOCK_ADD)
        STOCKITEM(wxID_APPLY,            GTK_STOCK_APPLY)
        STOCKITEM(wxID_BACKWARD,         GTK_STOCK_GO_BACK)
        STOCKITEM(wxID_BOLD,             GTK_STOCK_BOLD)
        STOCKITEM(wxID_BOTTOM,           GTK_STOCK_GOTO_BOTTOM)
        STOCKITEM(wxID_CANCEL,           GTK_STOCK_CANCEL)
        STOCKITEM(wxID_CDROM,            GTK_STOCK_CDROM)
        STOCKITEM(wxID_CLEAR,            GTK_STOCK_CLEAR)
        STOCKITEM(wxID_CLOSE,            GTK_STOCK_CLOSE)
        STOCKITEM(wxID_CONVERT,          GTK_STOCK_CONVERT)
        STOCKITEM(wxID_COPY,             GTK_STOCK_COPY)
        STOCKITEM(wxID_CUT,              GTK_STOCK_CUT)
        STOCKITEM(wxID_DELETE,           GTK_STOCK_DELETE)
        STOCKITEM(wxID_DOWN,             GTK_STOCK_GO_DOWN)
        STOCKITEM(wxID_EDIT,             GTK_STOCK_EDIT)
        STOCKITEM(wxID_EXECUTE,          GTK_STOCK_EXECUTE)
        STOCKITEM(wxID_EXIT,             GTK_STOCK_QUIT)
        STOCKITEM(wxID_FILE,             GTK_STOCK_FILE)
        STOCKITEM(wxID_FIND,             GTK_STOCK_FIND)
        STOCKITEM(wxID_FIRST,            GTK_STOCK_GOTO_FIRST)
        STOCKITEM(wxID_FLOPPY,           GTK_STOCK_FLOPPY)
        STOCKITEM(wxID_FORWARD,          GTK_STOCK_GO_FORWARD)
        STOCKITEM(wxID_HARDDISK,         GTK_STOCK_HARDDISK)
        STOCKITEM(wxID_HELP,             GTK_STOCK_HELP)
        STOCKITEM(wxID_HOME,             GTK_STOCK_HOME)
        STOCKITEM(wxID_INDENT,           GTK_STOCK_INDENT)
        STOCKITEM(wxID_INDEX,            GTK_STOCK_INDEX)
        STOCKITEM_28(wxID_INFO,           GTK_STOCK_INFO)
        STOCKITEM(wxID_ITALIC,           GTK_STOCK_ITALIC)
        STOCKITEM(wxID_JUMP_TO,          GTK_STOCK_JUMP_TO)
        STOCKITEM(wxID_JUSTIFY_CENTER,   GTK_STOCK_JUSTIFY_CENTER)
        STOCKITEM(wxID_JUSTIFY_FILL,     GTK_STOCK_JUSTIFY_FILL)
        STOCKITEM(wxID_JUSTIFY_LEFT,     GTK_STOCK_JUSTIFY_LEFT)
        STOCKITEM(wxID_JUSTIFY_RIGHT,    GTK_STOCK_JUSTIFY_RIGHT)
        STOCKITEM(wxID_LAST,             GTK_STOCK_GOTO_LAST)
        STOCKITEM(wxID_NETWORK,          GTK_STOCK_NETWORK)
        STOCKITEM(wxID_NEW,              GTK_STOCK_NEW)
        STOCKITEM(wxID_NO,               GTK_STOCK_NO)
        STOCKITEM(wxID_OK,               GTK_STOCK_OK)
        STOCKITEM(wxID_OPEN,             GTK_STOCK_OPEN)
        STOCKITEM(wxID_PASTE,            GTK_STOCK_PASTE)
        STOCKITEM(wxID_PREFERENCES,      GTK_STOCK_PREFERENCES)
        STOCKITEM(wxID_PREVIEW,          GTK_STOCK_PRINT_PREVIEW)
        STOCKITEM(wxID_PRINT,            GTK_STOCK_PRINT)
        STOCKITEM(wxID_PROPERTIES,       GTK_STOCK_PROPERTIES)
        STOCKITEM(wxID_REDO,             GTK_STOCK_REDO)
        STOCKITEM(wxID_REFRESH,          GTK_STOCK_REFRESH)
        STOCKITEM(wxID_REMOVE,           GTK_STOCK_REMOVE)
        STOCKITEM(wxID_REPLACE,          GTK_STOCK_FIND_AND_REPLACE)
        STOCKITEM(wxID_REVERT_TO_SAVED,  GTK_STOCK_REVERT_TO_SAVED)
        STOCKITEM(wxID_SAVE,             GTK_STOCK_SAVE)
        STOCKITEM(wxID_SAVEAS,           GTK_STOCK_SAVE_AS)
        STOCKITEM_210(wxID_SELECTALL,    GTK_STOCK_SELECT_ALL)
        STOCKITEM(wxID_SELECT_COLOR,     GTK_STOCK_SELECT_COLOR)
        STOCKITEM(wxID_SELECT_FONT,      GTK_STOCK_SELECT_FONT)
        STOCKITEM(wxID_SORT_ASCENDING,   GTK_STOCK_SORT_ASCENDING)
        STOCKITEM(wxID_SORT_DESCENDING,  GTK_STOCK_SORT_DESCENDING)
        STOCKITEM(wxID_SPELL_CHECK,      GTK_STOCK_SPELL_CHECK)
        STOCKITEM(wxID_STOP,             GTK_STOCK_STOP)
        STOCKITEM(wxID_STRIKETHROUGH,    GTK_STOCK_STRIKETHROUGH)
        STOCKITEM(wxID_TOP,              GTK_STOCK_GOTO_TOP)
        STOCKITEM(wxID_UNDELETE,         GTK_STOCK_UNDELETE)
        STOCKITEM(wxID_UNDERLINE,        GTK_STOCK_UNDERLINE)
        STOCKITEM(wxID_UNDO,             GTK_STOCK_UNDO)
        STOCKITEM(wxID_UNINDENT,         GTK_STOCK_UNINDENT)
        STOCKITEM(wxID_UP,               GTK_STOCK_GO_UP)
        STOCKITEM(wxID_YES,              GTK_STOCK_YES)
        STOCKITEM(wxID_ZOOM_100,         GTK_STOCK_ZOOM_100)
        STOCKITEM(wxID_ZOOM_FIT,         GTK_STOCK_ZOOM_FIT)
        STOCKITEM(wxID_ZOOM_IN,          GTK_STOCK_ZOOM_IN)
        STOCKITEM(wxID_ZOOM_OUT,         GTK_STOCK_ZOOM_OUT)

        default:
            break;
    }

    #undef STOCKITEM

    return nullptr;
}
wxGCC_WARNING_RESTORE(cast-qual)
wxGCC_WARNING_RESTORE()
#endif // !__WXGTK4__

#endif // wxUSE_MENUS
