#!/bin/bash

# configure is generated from configure.ac, and which autoconf generated it
# shows in every line of the result: upstream ships 2.69, and regenerating
# with a newer one rewrites some 20000 lines that are nobody's change. Those
# lines conflict with every other patch in flight and hide the 38 lines of
# configure.ac that are actually ours. See #106, gate 1.
#
# So this checks two things: that configure is what configure.ac says it
# should be, and that it was made by the version upstream uses.
#
# Like the other generated-file checks here, a failure leaves the file
# regenerated in the working tree: that is the fix, ready to be committed.

cd $(dirname "$0")/../..

AUTOCONF_WANTED=2.69

rc=0

autoconf=$(command -v autoconf$AUTOCONF_WANTED)
if [ -z "$autoconf" ] ; then
    # Fall back to plain autoconf, but only if it is the right version:
    # regenerating with the wrong one is worse than not checking at all.
    version=$(autoconf --version 2>/dev/null | head -1 |
                  grep -oE '[0-9]+\.[0-9]+')
    if [ "$version" = "$AUTOCONF_WANTED" ] ; then
        autoconf=$(command -v autoconf)
    else
        echo "ERROR - autoconf $AUTOCONF_WANTED is needed to check configure"
        echo "        (found ${version:-none});" \
             "install autoconf$AUTOCONF_WANTED"
        exit 1
    fi
fi

# The header configure carries names the version that wrote it, so this
# catches a configure regenerated elsewhere with a different autoconf even
# when configure.ac has not moved.
generated_by="Generated by GNU Autoconf $AUTOCONF_WANTED"
if ! head -20 configure | grep -q "$generated_by" ; then
    echo "ERROR - configure was not generated by autoconf $AUTOCONF_WANTED:"
    head -20 configure | grep -i 'generated by' | sed 's/^/        /'
    rc=$((rc+1))
fi

# autoconf serves a cached result when it thinks nothing changed, and it
# decides that from timestamps: a checkout can leave configure.ac older than
# the cache and get the previous output back. Regenerating over the top of
# that would compare a file with itself and pass whatever the input said.
rm -rf autom4te.cache

"$autoconf" -o configure configure.ac || exit 1

if ! git diff --quiet -- configure ; then
    echo "ERROR - configure was out of date with configure.ac and has been"
    echo "        regenerated; commit the result"
    rc=$((rc+1))
fi

exit $rc
